### ISSUE TITLE
ProtocolError 500 Internal Server Error after update to 	23.1.4_1

### ISSUE THREAD

**Issue by JimmyMPage** [travisghansen/hass-opnsense#72] opened 2023-03-22 12:54 UTC
I am experiencing this error:

"Unexpected error fetching PF-Router OPNsense state data: <ProtocolError for ********@10.0.4.1/xmlrpc.php: 500 Internal Server Error>"

It seemed to start after a recent OPNSense update (at least, it seemed to occur after I told the hass-opnsense to update to the latest firmware). I tried a full re-install of both the plugin on OPNSense and the integration on HASS, but it didn't fix it.

**Comment by travisghansen** [comment] 2023-03-22 12:58
Duplicate of #68 and #70

**Closed by travisghansen** 2023-03-22 12:58 UTC
