### ISSUE TITLE
Unable to register new server

### ISSUE THREAD

**Issue by 3suns-org** [travisghansen/hass-opnsense#19] opened 2021-12-22 15:39 UTC
I am getting the following error when registering my opnsense server - [%key:common::config_flow::error::unknown%]

**Comment by travisghansen** [comment] 2021-12-22 15:49
Welcome! Check the hass logs and you should see a relevant entry with further details and send that over.

**Comment by alexdelprete** [comment] 2021-12-22 15:50
> I am getting the following error when registering my opnsense server - [%key:common::config_flow::error::unknown%]

Did you install the addon on OPNsense?

**Comment by 3suns-org** [comment] 2021-12-22 15:54
> Welcome! Check the hass logs and you should see a relevant entry with further details and send that over.

Here is the additional data. Let me know if there is anything else I can provide.

This error originated from a custom integration.

Logger: custom_components.opnsense.config_flow
Source: custom_components/opnsense/config_flow.py:140
Integration: opnsense (documentation, issues)
First occurred: 7:38:28 AM (1 occurrences)
Last logged: 7:38:28 AM

Unexpected err=gaierror(-3, 'Try again'), type(err)=<class 'socket.gaierror'>

**Comment by 3suns-org** [comment] 2021-12-22 15:54
> > I am getting the following error when registering my opnsense server - [%key:common::config_flow::error::unknown%]
> 
> Did you install the addon on OPNsense?

Yes -  I followed the instructions here - https://github.com/travisghansen/hass-opnsense

**Comment by travisghansen** [comment] 2021-12-22 16:01
That error seems to indicate an issue with the url/hostname you entered for the opnsense url…can you send what you’re using for the url by chance? Or anonymize it and send over at least the format/syntax you are attempting?

**Comment by 3suns-org** [comment] 2021-12-22 16:26
I have two devices and have been using https://ipaddress. I tried the backup device and was able to register but the primary device still errors.

**Comment by travisghansen** [comment] 2021-12-22 17:44
Yeah not sure. It can't 'get address info' which is a pretty low-level error. Can you ping the ip of the primary device from the hass machine?

**Comment by alexdelprete** [comment] 2021-12-22 18:14
From the hass pc, try `telnet ip_opnsense 80` to check if it can open port 80 on opnsense IP address.

**Comment by 3suns-org** [comment] 2021-12-22 19:54
Sorry for my newbie questions but how do I do that?

The gateway is the same address that I am using (which is accessible). I was also able to add adguard to the same device (different port of course) with no issue.

**Comment by travisghansen** [comment] 2021-12-22 20:11
That is strange. Did you try multiple times and always get the same error or just the once? The error generally speaking is (or can be) sporadic/temporary  and short lived vs some fundamental issue that must be fixed.

**Comment by 3suns-org** [comment] 2021-12-22 20:13
I tried repeatedly and after reboots. I also tried a virtual address as well as various ips across different vlans all with the same result.

**Comment by travisghansen** [comment] 2021-12-22 20:15
Always with ip or have you been using hostname?

**Comment by 3suns-org** [comment] 2021-12-22 20:26
I have tried both.
________________________________

**Comment by travisghansen** [comment] 2021-12-22 20:35
Can you try using curl to access the opnsense url from the hass machine console?

**Comment by 3suns-org** [comment] 2021-12-22 20:45
Sure but how do i run commands from the machine? I am at an Home assistant command line but that seems like the wrong place.
________________________________

**Comment by travisghansen** [comment] 2021-12-22 20:52
`curl -v ‘<url>’`

**Comment by 3suns-org** [comment] 2021-12-22 21:11
I think I am in the wrong window

FATA[0000] Error while executing rootCmd: unknown command "curl" for "ha"

Did you mean this?
               core
________________________________

**Comment by travisghansen** [comment] 2021-12-22 22:15
I’m not entirely sure how to get to a standard shell with hass os :(

**Comment by 3suns-org** [comment] 2021-12-22 23:26
Sadly we are in the same boat.


________________________________

**Comment by alexdelprete** [comment] 2021-12-22 23:52
You need to install the `SSH & Web Terminal` addon from the addons store: https://github.com/hassio-addons/addon-ssh

**Comment by 3suns-org** [comment] 2021-12-23 15:02
That seemed to work

[cid:6411c94a-f7d1-4c26-b956-2fe040c69179]
________________________________

**Comment by alexdelprete** [comment] 2021-12-24 01:07
> That seemed to work

What worked?

**Comment by 3suns-org** [comment] 2021-12-24 02:58
Running the curl command


________________________________

**Comment by alexdelprete** [comment] 2021-12-24 03:12
Can you show the output?

**Comment by 3suns-org** [comment] 2021-12-24 03:17
Sorry I did but it looks like it didn't make it. Uploading again. 
![image](https://user-images.githubusercontent.com/71104914/147311729-237a7695-d1ca-485a-a970-4c70b9654e1e.png)

**Comment by alexdelprete** [comment] 2021-12-24 03:19
Certificate issue.

Can you try curl on the other system you said the integration works with? Please report the output of that.

**Comment by 3suns-org** [comment] 2021-12-25 21:20
Looks identical to me 

![image](https://user-images.githubusercontent.com/71104914/147393774-b9ec8b6e-e5ae-43ac-950f-0cc9e13b7cca.png)

**Comment by travisghansen** [comment] 2021-12-25 21:27
In the integration did uncheck ‘verify ssl certificate’ when trying to add the server?

**Comment by 3suns-org** [comment] 2021-12-25 21:28
Yes


________________________________

**Comment by travisghansen** [comment] 2021-12-25 21:39
Run the curl command again but add `-k` and send the output as well.

**Comment by 3suns-org** [comment] 2021-12-25 21:53
192.168.2.3 is successful device and 192.168.2.2 is unsuccessful device

![image](https://user-images.githubusercontent.com/71104914/147394152-0fc4495d-82b3-4a6c-9b83-79d961a50b76.png)

![image](https://user-images.githubusercontent.com/71104914/147394156-8e4cbe44-0945-4d39-b599-dfe3f2c1f9e9.png)

**Comment by travisghansen** [comment] 2021-12-25 22:11
Yeah that’s pretty crazy :( I’m not sure what advice to give at this point. The failure is a pretty low level failure but seems to only be happening running in python and not generally for the node.

Does your username and/or password have any crazy characters in it?

**Comment by 3suns-org** [comment] 2021-12-25 22:23
Nothing crazy in the user name and password and they are the same between the working and non working devices.


________________________________

**Comment by travisghansen** [comment] 2021-12-25 22:28
I'm at a loss. I don't think that error should even come into play when using IP address anyway..it's all a bit crazy :(

**Comment by alexdelprete** [comment] 2021-12-26 00:06
Travis, maybe let him activate debug in logger for the component? So we can see some details at the python/component level.

**Comment by travisghansen** [comment] 2021-12-26 00:16
Perhaps. It’s such a low level error though that I have doubts it will help. The error code is coming from c-level hostname resolution…it’s failing on pretty fundamental stuff that’s generally speaking well outside the scope of the integration.

**Comment by alexdelprete** [comment] 2021-12-26 00:47
Did a quick search on the forum: there are a lot of cases, but all seem to point to network issues. Firewall, dhcp/mac address mismatch issues, etc.

Hard to debug for us, but it looks like a network problem to be addressed.

**Comment by alexdelprete** [comment] 2021-12-26 00:52
Found this, pointing to a temporary reverse DNS lookup problem:

`gaierror is "getaddrinfo error", and -3 is "EAI_AGAIN: The name server returned a temporary failure indication. Try again later." Your DNS is acting up. Catching socket.gaierror and retrying is a good solution.`

**Comment by travisghansen** [comment] 2021-12-26 00:55
Yeah in some circumstances a retry may make sense, but the user is getting the issue consistently indicating it’s not intermittent which makes it even more strange.

**Comment by alexdelprete** [comment] 2021-12-26 01:01
> 192.168.2.3 is successful device and 192.168.2.2 is unsuccessful device

could you show us the settings of web gui in SYSTEMS:SETTINGS:ADMINISTRATION in OPNsense? I'm thinking in particular to the `DNS Rebind Check` setting.

![image](https://user-images.githubusercontent.com/7027842/147396354-3ecbe853-50a4-4f0e-91eb-ba4257ef64f6.png)

**Comment by alexdelprete** [comment] 2021-12-27 09:13
@travisghansen I recently switched to SSL for the GUI, and I noticed I had a lot of unavailable responses from the component, thinking about this issue we're discussing here, I reverted to HTTP again, no SSL, and all the unavailable responses have disappeared, the component is working much more reliably when querying the php plugin.

I think there might be some issues regarding the SSL connection...maybe those security options of OPNsense play a role with that, I'm leaving HTTP for now, also because it's on LAN, so I don't have big security concerns.

**Comment by 3suns-org** [comment] 2021-12-28 15:09
Settings are the same on both systems-

![image](https://user-images.githubusercontent.com/71104914/147579695-b5d050c1-101e-4f64-839d-570c353b96ea.png)

![image](https://user-images.githubusercontent.com/71104914/147579714-a6eb46c5-865b-4b47-9c49-77023b9ab0ef.png)
.

Also I tried changing to HTTP and got the same error messages.

**Comment by alexdelprete** [comment] 2021-12-28 15:12
If it can't connect in HTTP, there's some serious low-level issue on the networking side. I noticed some issues with HTTPS sometims returning unavailable status, but it can always connect. Your issue seems a different one.

**Comment by 3suns-org** [comment] 2021-12-28 15:14
The two systems in question are in an HA config and the primary device is the one I cant get to connect but all of the settings are identical because they are syncing.

**Comment by alexdelprete** [comment] 2021-12-28 15:15
If it's a sort of cluster, why do you need to monitor both? is it active-active or active-passive?

**Comment by 3suns-org** [comment] 2021-12-28 15:16
Its active-passive and I can only monitor the passive node.

**Comment by alexdelprete** [comment] 2021-12-28 15:17
got you. I wonder if the cluster configuration of OPNsense is doing some low-level stuff that interferes. I don't know how that works, never analyzed it.

**Comment by travisghansen** [comment] 2021-12-28 15:18
This will be a great test if we can get you going :)

Is there a floating address for the current active node at 192.168.2.1?

**Comment by 3suns-org** [comment] 2021-12-28 15:21
There are no floating rules that call out that address. .1 is the virtual address that moves back and forth. .2 is the active and .3 is the passive. I have tried both the virtual and active addresses but have only been using the active address in all of my tests.

**Comment by alexdelprete** [comment] 2021-12-28 15:26
And the problem is with the virtual address .1 or .2 ?

**Comment by travisghansen** [comment] 2021-12-28 15:26
Yeah ok makes sense. I assume that’s a carp address?

Do you see anything in the firewall logs? Even just unclean closed connections?

If you fail over to the backup node does .3 still work? Does .3 stop working if you fail over and .2 begins to work?

**Comment by alexdelprete** [comment] 2021-12-28 15:27
> 

Technically, the only instance to monitor should be .1, the virtual IP of the active node.

**Comment by travisghansen** [comment] 2021-12-28 15:38
Not necessarily. Although non-monitoring activities (changing rules etc) should be limited to .2 as updates always stream downward from the primary regardless of which is currently active. There is benefit to monitoring each distinctly as carp status etc would be good to track.

**Comment by 3suns-org** [comment] 2021-12-28 15:39
Nothing shows up in the firewall. The only traffic I see from that host is to the passive node. If I failover (depending on how its done) .2 or .3 will remain active if they are still up and online. Those addresses belong to the individual nodes. If I take the interface or machine offline, then they will be unavailable.

**Comment by 3suns-org** [comment] 2021-12-28 15:40
And an per the earlier question, the problem is with the Carp/Virtual address of .1 and also the active node .2

**Comment by travisghansen** [comment] 2021-12-28 15:42
Right. Have you tried failing over to see if it alters the observed behavior of ha after doing the failover?

**Comment by 3suns-org** [comment] 2021-12-28 15:43
With respect to those IPs specifically?

**Comment by alexdelprete** [comment] 2021-12-28 15:43
> Not necessarily. Although non-monitoring activities (changing rules etc) should be limited to .2 as updates always stream downward from the primary regardless of which is currently active. There is benefit to monitoring each distinctly as carp status etc would be good to track.

I was referring to monitoring activities. Regarding the primary/secondary: what happens if primary isn't working anymore? You can't make changes on secondary? Ypu promote it to primary? So the sync is not bidirectional, it's always from primary to secondary.

**Comment by 3suns-org** [comment] 2021-12-28 15:45
I would have to do any of that testing at a later time because one of my interfaces does not failover and its active so it will be disruptive.

**Comment by travisghansen** [comment] 2021-12-28 16:09
> Yes, I was referring to monitoring activities. Regarding the primary/secondary: what happens if primary isn't working anymore? You can't make changes on secondary? You promote it to primary? So the sync is not bidirectional, it's always from primary to secondary.

Config changes flow in 1 direction, so if the secondary node is the current active node generally you would wait until the primary node is available again (even if it's the passive node) to make firewall changes etc.

Some aspects are bidirectional (tcp states, etc), but **config** changes only flow 'downward'. So you could hypothetically have more than 2 nodes and the flow is like this 1 -> 2 -> 3 -> n. If you may change at any node besides 1 only the nodes downstream will receive the updates.

**Comment by travisghansen** [comment] 2021-12-28 16:10
> I would have to do any of that testing at a later time because one of my interfaces does not failover and its active so it will be disruptive.

Sounds good. If you can't no big deal but was just a thought to test.

**Comment by alexdelprete** [comment] 2022-06-05 02:12
@3suns-org did you manage to find the problem?

**Comment by 3suns-org** [comment] 2022-06-05 19:42
No I did not.

**Comment by blockcrafter21** [comment] 2022-06-30 16:42
Same on my side

**Comment by travisghansen** [comment] 2022-07-06 21:33
@blockcrafter21 you also have a highly available configuration? I'm doing an little maintenance on this project this week so any info you can provide is appreciated!

**Comment by blockcrafter21** [comment] 2022-07-07 04:25
> @blockcrafter21 you also have a highly available configuration? I'm doing an little maintenance on this project this week so any info you can provide is appreciated!

No, not highly available, but both HA and Opnsense are Virtualized.

**Comment by mdrichardson** [comment] 2022-08-15 23:37
I also seem to be having this issue. High Availability not configured. Firewall logs show the  call is allowed through. the only setup instruction I *didn't* follow was that I didn't see permissions specifically for "System - HA node sync" and just allowed "xmlrpc", instead.

**Comment by travisghansen** [comment] 2022-08-16 03:36
This has been around for while. Can you all send over the most recent back traces/logs when the error occurs and screenshots of the gui etc? Having some fresh data may be helpful.

**Comment by mdrichardson** [comment] 2022-08-16 16:53
I've been able to generate a couple of different errors through various connection methods (ip address, domain, ssl on/off, etc):

**Hass Logs**

```
2022-08-16 09:43:17.803 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=RemoteDisconnected('Remote end closed connection without response'), type(err)=<class 'http.client.RemoteDisconnected'>
2022-08-16 09:43:26.680 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=TypeError('string indices must be integers'), type(err)=<class 'TypeError'>
```

**OPNsense Logs**

```
2022-08-16T09:47:42-07:00 | Informational | lighttpd | 172.16.11.1 <domain redacted> - [16/Aug/2022:09:47:42 -0700] "POST /xmlrpc.php HTTP/1.1" 200 146 "-" "Python-xmlrpc/3.10"

2022-08-16T09:48:36-07:00 | Error | lighttpd | (mod_openssl.c.3273) SSL: 1 error:1408F09C:SSL routines:ssl3_get_record:http request (172.16.11.200)
```

Let me know if there's other logs you'd like to see

![image](https://user-images.githubusercontent.com/40401643/184934809-8f966883-9672-470b-adbd-f62d40af5eaa.png)
![image](https://user-images.githubusercontent.com/40401643/184934890-54c8c2fc-0afc-4f0b-9cd1-65c340d4a58f.png)
![image](https://user-images.githubusercontent.com/40401643/184935014-7197aa23-f26b-4604-ae72-917cf8a5aca8.png)
![image](https://user-images.githubusercontent.com/40401643/184935375-3b948aa4-fbdb-4113-aa2a-7ee39ae412c0.png)

**Comment by travisghansen** [comment] 2022-08-16 17:30
How is the package misconfigured? I have no idea what that even means as there is no configuration for the package.

**Comment by travisghansen** [comment] 2022-08-16 17:55
Same as this? https://github.com/travisghansen/hass-opnsense/issues/33

**Comment by travisghansen** [comment] 2022-08-16 18:01
Did you update permissions and now it works?

**Comment by mdrichardson** [comment] 2022-08-16 18:02
> Did you update permissions and now it works?

Update permissions? Should it be different than what I have above? And no, currently does not work.

**Comment by travisghansen** [comment] 2022-08-16 18:09
https://github.com/travisghansen/hass-opnsense/issues/33#issuecomment-1209394213

**Comment by mdrichardson** [comment] 2022-08-16 18:16
Yep, I've got that in one of the images, above. I just added `System: High Availability`, too, since that was the closest to `System - HA node sync` in the instructions:

![image](https://user-images.githubusercontent.com/40401643/184950319-d9c53a66-f32b-4ff8-8a68-595c9d9c3788.png)

**Comment by alexdelprete** [comment] 2022-08-16 18:20
I noticed you have HTTPS enabled in opnsense web gui, but you used http:// in the integration configuration. Can you please check that?

**Comment by mdrichardson** [comment] 2022-08-16 18:22
@alexdelprete You've got to be kidding. I swear I tried that. All is working, now 🤦‍♂️

**Comment by alexdelprete** [comment] 2022-08-16 18:23
> My `crowdsec` package says that as well. I _believe_ it just says this when you install manually from the CLI from a non-standard repo.

That's not the reason, my mimugmail plugins report installed as expected. Check your opnsense configuration. What version of opnsense do you use?

**Comment by alexdelprete** [comment] 2022-08-16 18:24
> You've got to be kidding. I swear I tried that. All is working, now 🤦‍♂️

I noticed from your opnsense logs, the webserver was closing the connection, and then SSL error. :)

```
2022-08-16T09:47:42-07:00 | Informational | lighttpd | 172.16.11.1 <domain redacted> - [16/Aug/2022:09:47:42 -0700] "POST /xmlrpc.php HTTP/1.1" 200 146 "-" "Python-xmlrpc/3.10"

2022-08-16T09:48:36-07:00 | Error | lighttpd | (mod_openssl.c.3273) SSL: 1 error:1408F09C:SSL routines:ssl3_get_record:http request (172.16.11.200)
```

**Comment by travisghansen** [comment] 2022-08-16 18:43
So it would be good to figure out what error was spewed in hass and what specific permission needed to be added to resolve the issue.

Then we can update the docs and I can code the error messages to return more meaningful messages to the user/ui.

**Comment by alexdelprete** [comment] 2022-08-16 19:21
I thought we confirmed that the only permission needed is XMLRpc. I can double-check this.

For the specific HASS error: maybe @mdrichardson can help us checking hass logs and report the specific error.

**Comment by travisghansen** [comment] 2022-08-16 19:31
I think it’s just json encoded values.

**Comment by mdrichardson** [comment] 2022-08-16 19:44
> For the specific HASS error: maybe @mdrichardson can help us checking hass logs and report the specific error.

Hass log relevant to that is below. Unfortunately, it's not terribly specific.

```
2022-08-16 09:43:17.803 ERROR (MainThread) [custom_components.opnsense.config_flow] Unexpected err=RemoteDisconnected('Remote end closed connection without response'), type(err)=<class 'http.client.RemoteDisconnected'>
```

**Comment by travisghansen** [comment] 2022-08-16 19:48
That’s the error for using http instead of https right?

**Comment by mdrichardson** [comment] 2022-08-16 19:48
Yes.

**Comment by alexdelprete** [comment] 2022-08-16 22:10
> That’s the error for using http instead of https right?

It's a generic remote disconnection error. The cause could also be something else. In his case, it was the non SSL connection.

**Comment by travisghansen** [comment] 2022-08-16 22:21
Understood about the connection error.

**Comment by alexdelprete** [comment] 2022-08-16 23:14
Travis, I created a new user with only one privilege: XMLrpc.

I restarted HA after configuring the new user, and everything seems to be working fine, except for the update sensor (`update.opnsense_firmware_updates_available`), which has now become `unavailable`. Maybe it's not related to the privileges...but I wanted to know your opinion.

![image](https://user-images.githubusercontent.com/7027842/185000696-f725fb29-04d5-4940-a8b2-c01516b4de30.png)

**Comment by travisghansen** [comment] 2022-08-17 03:19
Yeah there are several things that use the rest api which would require appropriate permissions for that. An audit of everything would be a very good thing to have so it’s not so vague what permissions are needed and when.

**Comment by alexdelprete** [comment] 2022-08-17 11:33
Makes sense.

Question: when I add the `System High Availability` privilege, it says it allows to execute the `system_hasync.php` script. That works because the integration uses that through the REST API?

How can I help you with this audit? If you explain me what to do I'll try to do it.

**Comment by travisghansen** [comment] 2022-08-17 13:10
That’s honestly probably sufficient but we could check in the client for any methods using `self._get` or `self._post` and determine which permissions are required for those specifically (would be good to document those in the actual code).

Beyond that, we would need to check and make sure the integration actually uses those methods and document the necessary permissions as actually used by the integration currently in the readme

**Comment by rwijbenga** [comment] 2022-08-17 13:27
@alexdelprete 

Could you maybe share your dashboard used to display the OPNsense data so nicely? :)

**Comment by Iceman248** [comment] 2022-08-17 21:13
Having issue getting this working. HA mentions integration added successfully, then I get this error no matter what I try, with and without the HA permissions on top of XMLRPC. SSL cert not valid, just the self signed, but I unchecked verify it.

`Retrying setup: <ProtocolError for <key>:<secret>@<OPNsense URL>/xmlrpc.php: 500 Internal Server `Error>``

**Comment by Iceman248** [comment] 2022-08-17 21:39
Saw this error over and over in my OPNsense logs.

[17-Aug-2022 17:01:30] PHP Fatal error:  Uncaught Error: Call to undefined function are_notices_pending() in /usr/local/etc/inc/xmlrpc/hass.inc(12) : eval()'d code:6
Stack trace:
#0 /usr/local/etc/inc/xmlrpc/hass.inc(12): eval()
#1 /usr/local/opnsense/contrib/IXR/IXR_Library.php(446): exec_php_xmlrpc('\nini_set('displ...')
#2 /usr/local/opnsense/contrib/IXR/IXR_Library.php(384): IXR_Server->call('opnsense.exec_p...', '\nini_set('displ...')
#3 /usr/local/opnsense/contrib/IXR/IXR_Library.php(357): IXR_Server->serve('__construct(Array)
#5 /usr/local/www/xmlrpc.php(104): XMLRPCServer->start()
#6 {main}

**Comment by travisghansen** [comment] 2022-08-17 22:05
Yeah, that's not a permissions error for sure. I have no idea why the method would work without explicitly including in all the other installs but not yours :( I've got a few changes queued up and I can add that to the list.

**Comment by travisghansen** [comment] 2022-08-17 22:22
OK, just push `v0.1.3`, give that a try and see if it fixes those errors.

**Comment by alexdelprete** [comment] 2022-08-17 22:50
> Having issue getting this working. HA mentions integration added successfully, then I get this error no matter what I try

Did you install the OPNsense plugin as per readme instructions?

**Comment by Iceman248** [comment] 2022-08-17 23:05
No, still getting the same thing.

Yes, I installed the OPNsense plugin.

**Comment by Iceman248** [comment] 2022-08-17 23:13
For what it's worth, using HTTP instead of HTTPS with OPNsense and making the user an admin user yielded same result.

**Comment by alexdelprete** [comment] 2022-08-17 23:16
What version of OPNsense? Please double check the installation of the plugin and make sure the user has permissions. Never saw these kind of errors, looks like the plugin is not able to do what it's supposed to on OPNsense, either for permissions issues or something else.

**Comment by Iceman248** [comment] 2022-08-17 23:20
Latest, 22.7.2. What do you mean by making sure the user has permissions? The XMLRPC/HA stuff?

Plugin shows installed. Not sure if I have rebooted since then, not sure if that was necessary.

**Comment by alexdelprete** [comment] 2022-08-17 23:20
@travisghansen Ok, the problem is the 22.7.2 update: they changed something related to the notice system.

```
system: replace static notices system with a shared one based on MVC/API code
```

**Comment by travisghansen** [comment] 2022-08-17 23:23
Well that’s fun for a point release lol! That will likely take some time to rework.

**Comment by alexdelprete** [comment] 2022-08-17 23:26
> That will likely take some time to rework.

I imagined that, hope it won't require a total rework. I was thinking about going back to 22.7.1 but I don't like rolling back unless it's an urgent thing. Next time, before updating, I'll ask you to first test it in your dev environment. :)

**Comment by Iceman248** [comment] 2022-08-17 23:34
Pooey. Well, at least we found out the issue. I just deployed this OPNsense today. Figures. 🤦‍♂️

**Comment by alexdelprete** [comment] 2022-08-17 23:41
And I updated to 22.7.2 while I was replying to you about the issue. :)

**Comment by travisghansen** [comment] 2022-08-17 23:41
You could comment 324-327 and it will probably make it start working again: https://github.com/travisghansen/hass-opnsense/blob/main/custom_components/opnsense/__init__.py#L324

**Comment by alexdelprete** [comment] 2022-08-17 23:43
could you push a beta release with those lines commented, as a workaround?

**Comment by travisghansen** [comment] 2022-08-17 23:52
Let’s create a new issue. I won’t be able to take a look for several hours.

**Comment by Iceman248** [comment] 2022-08-18 00:08
> You could comment 324-327 and it will probably make it start working again: https://github.com/travisghansen/hass-opnsense/blob/main/custom_components/opnsense/__init__.py#L324

Woohoo! Thanks, that worked.

**Comment by alexdelprete** [comment] 2022-08-18 01:31
> or any methods using `self._get` or `self._post` and determine which permissions are required for those specifically (would be good to document those in the actual code).

Just to make sure I understand correctly, I see several types of `self._get` and `self._post`:

Proxy (don't know what it is, probably the calls to the plugin?)
```
1. self._get_proxy().opnsense.restore_config_section(params)
2. self._get_proxy().opnsense.exec_php(script)
3. self._get_proxy().opnsense.firmware_version()
4. self._get_proxy().opnsense.list_services()
5. self._get_proxy().opnsense.start_service(params)
6. self._get_proxy().opnsense.stop_service(params)
7. self._get_proxy().opnsense.restart_service(params)
```

REST calls?
```
8. self._get("/api/core/firmware/status")
9. self._get("/api/core/firmware/upgradestatus")
10. self._post("/api/core/firmware/check")
11. self._post("/api/core/firmware/update")
12. self._post("/api/core/firmware/upgrade")
13. self._post("/api/core/firmware/upgradestatus")
14. self._post("/api/core/firmware/changelog/" + version)
```

Don't know :)
```
15. self._get_config_section("interfaces")
```

If you tell me which ones I need to look for in opnsense documentation, I'll do it...I think all the REST calls (get/post) are ok with the `System:Firmware` privilege.

**Comment by alexdelprete** [comment] 2022-08-18 01:38
> You could comment 324-327 and it will probably make it start working again: https://github.com/travisghansen/hass-opnsense/blob/main/custom_components/opnsense/__init__.py#L324

Seems to be working, except for some CPU sensors that now are not available:

![image](https://user-images.githubusercontent.com/7027842/185273218-85e0bbe2-5a5e-44da-8a10-c0c387a3b046.png)

**Comment by Iceman248** [comment] 2022-08-18 01:54
> > You could comment 324-327 and it will probably make it start working again: https://github.com/travisghansen/hass-opnsense/blob/main/custom_components/opnsense/__init__.py#L324
> 
> Seems to be working, except for some CPU sensors that now are not available:
> 
> ![image](https://user-images.githubusercontent.com/7027842/185273218-85e0bbe2-5a5e-44da-8a10-c0c387a3b046.png)

My load sensors work, but they are labeled "System", not CPU. I didn't have ones labeled "CPU" specifically.

**Comment by alexdelprete** [comment] 2022-08-18 01:58
Yup, changes were introduced in v0.1.3, updated without checking the changelog. :)

What a messy night for me...luckily nothing too serious. :)

**Comment by travisghansen** [comment] 2022-08-18 04:17
I removed the CPU sensors since technically they aren't really cpu load, and they also are not percentages so new sensors have taken their place. I've also released a new version disabling the notice feature for now until it can be reworked.

**Comment by alexdelprete** [comment] 2022-08-18 04:19
> I removed the CPU sensors since technically they aren't really cpu load

Makes perfectly sense.

> I've also released a new version disabling the notice feature for now until it can be reworked.

Tested it now, it's working fine. Thanks.

**Comment by alexdelprete** [comment] 2022-08-18 15:34
> Could you maybe share your dashboard used to display the OPNsense data so nicely? :)

Here's the first column:

<details>
```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: update.opnsense_firmware_updates_available
        name: Firmware Updates Available
      - entity: sensor.opnsense_system_boottime
        name: System Boottime
      - entity: binary_sensor.opnsense_pending_notices_present
        name: Pending Notices Present
      - entity: sensor.opnsense_system_load_average_five_minute
        name: System Load Average Five Minute
      - entity: sensor.opnsense_filesystem_used_percentage_slash
        name: Filesystem Used Percentage slash
      - entity: sensor.opnsense_memory_used_percentage
        name: Memory Used Percentage
      - entity: sensor.opnsense_pf_state_table_used_percentage
        name: Pf State Table Used Percentage
    title: OPNsense - system
  - type: entities
    entities:
      - entity: sensor.opnsense_interface_wan_status
        name: Interface WAN status
      - entity: sensor.opnsense_gateway_wan_ftth_pppoe_status
        name: Gateway WAN_FTTH_PPPoE status
      - entity: sensor.opnsense_gateway_wan_ftth_pppoe_delay
        name: Gateway WAN_FTTH_PPPoE delay
      - entity: sensor.opnsense_gateway_wan_ftth_pppoe_loss
        name: Gateway WAN_FTTH_PPPoE loss
      - entity: sensor.opnsense_gateway_wan_ftth_pppoe_stddev
        name: Gateway WAN_FTTH_PPPoE stddev
    title: OPNsense - interfaces
    state_color: true
  - type: entities
    entities:
      - entity: >-
          switch.opnsense_nat_port_forward_rule_1639937591_1204_http_https_wan_traffic_to_traefik
      - entity: >-
          switch.opnsense_filter_rule_1634604446_6637_allow_icmp_echo_request_from_wan
      - entity: switch.opnsense_service_dhcpd_status
        name: Service dhcpd status
      - entity: switch.opnsense_service_ntpd_status
        name: Service ntpd status
      - entity: switch.opnsense_service_pf_status
        name: Service pf status
      - entity: switch.opnsense_service_routing_status
        name: Service routing status
      - entity: switch.opnsense_service_telegraf_status
        name: Service telegraf status
      - entity: switch.opnsense_service_unbound_status
        name: Service unbound status
    title: OPNsense - rules/services
```
</details>

The uptime and bandwidth graphs require two addons: `uptime-card` and `apexcharts-card`. Let me know if you want the code also for those two.

**Comment by travisghansen** [comment] 2022-08-18 17:20
notices have been fixed in a backward-compatible way and should function with `v0.1.5` as before.

**Comment by rwijbenga** [comment] 2022-08-18 20:55
@alexdelprete 

Super! That saves me a lot of time!

If you could share also the others... :) 

Thank you again!

**Comment by alexdelprete** [comment] 2022-08-19 00:26
> If you could share also the others

I updated the previous post with the source of the 2nd column. Install the addons first.

**Closed** 2023-01-18 05:03 UTC
