### ISSUE TITLE
Specific sensor unaviable, "update.opnsense_firmware_updates_available"

### ISSUE THREAD

**Issue by perdicaro** [travisghansen/hass-opnsense#54] opened 2023-01-11 08:07 UTC
Everything works fine, the only sensor I'm interested in using gives me it is not available, it's about the "update.opnsense_firmware_updates_available" any advice for this problem?

**Comment by travisghansen** [comment] 2023-01-11 09:57
Are there any logs indicating failure of some kind?

**Comment by perdicaro** [comment] 2023-01-11 10:16
where i can find logs opnsense ?

**Comment by perdicaro** [comment] 2023-01-11 10:19
> Are there any logs indicating failure of some 


where i can find logs for opnsense plugin?

**Comment by travisghansen** [comment] 2023-01-11 10:35
With the hass logs.

**Comment by alexdelprete** [comment] 2023-01-11 10:42
The unavailable update sensor was already reported some months ago by me and other people too. There's no clear error in HASS logs unfortunately. If there's some debugging we can do let me know.

**Comment by perdicaro** [comment] 2023-01-11 11:15
> The unavailable update sensor was already reported some months ago by me and other people too. There's no clear error in HASS logs unfortunately. If there's some debugging we can do let me know.

Exactly, I checked the logs and there are no errors

**Comment by perdicaro** [comment] 2023-01-11 11:18
> Il sensore di aggiornamento non disponibile è stato già segnalato alcuni mesi fa da me e da altre persone. Purtroppo non ci sono errori chiari nei registri HASS. Se c'è del debug, possiamo farmi sapere.
> 
> AGGIORNAMENTO: trova il vecchio post qui [# 25 (commento)](https://github.com/travisghansen/hass-opnsense/issues/25#issuecomment-1304342453)

I have debugging enabled in opnsense integrations, where can I find the log it creates?

**Comment by perdicaro** [comment] 2023-01-11 11:36
![2023-01-11 12_35_14-Impostazioni – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/211796536-e2ffac2f-3e34-49d2-b1fe-c4c6b30bb369.jpg)

**Comment by perdicaro** [comment] 2023-01-11 11:39
![2023-01-11 12_39_05-Panoramica – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/211797176-39ae21cf-5277-4657-98f0-9f65bb7581cc.jpg)

**Comment by alexdelprete** [comment] 2023-01-11 12:42
> I have debugging enabled in opnsense integrations, where can I find the log it creates?

It's an integration, doesn't have separate log, you should check HA logs...look for "opnsense"

**Comment by perdicaro** [comment] 2023-01-11 12:52
> > I have debugging enabled in opnsense integrations, where can I find the log it creates?
> 
> It's an integration, doesn't have separate log, you should check HA logs...look for "opnsense"

strange is not in the list, I can not find it
![2023-01-11 13_50_48-](https://user-images.githubusercontent.com/65085739/211811059-1e38b39e-96b5-4281-a5f5-89ae283f14f1.jpg)

**Comment by perdicaro** [comment] 2023-01-11 12:53
`2023-01-11 12:12:07.475 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 30 and 43
2023-01-11 12:12:07.763 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration opnsense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 12:12:07.766 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 12:12:07.768 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 12:12:07.769 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration discord_game which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 12:12:07.771 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 12:12:24.323 WARNING (MainThread) [homeassistant.config_entries] Config entry '10.10.10.62:19444' for hyperion integration not ready yet: None; Retrying in background
2023-01-11 12:12:35.198 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esphome-web-f01d44 @ 10.10.10.68: Error connecting to ('10.10.10.68', 6053): [Errno 113] Connect call failed ('10.10.10.68', 6053)
2023-01-11 12:12:37.944 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-01-11 12:12:38.522 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WLED Corridoio' for wled integration not ready yet: Invalid response from API: Error occurred while communicating with WLED device at 10.10.10.70; Retrying in background
2023-01-11 12:12:57.544 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-01-11 13:07:03.706 ERROR (MainThread) [homeassistant.components.octoprint] Error requesting octoprint-393bfec2373425cf73231b7a28e814ea data: Cannot connect to host 10.10.10.38:80 ssl:default [Connect call failed ('10.10.10.38', 80)]`

**Comment by alexdelprete** [comment] 2023-01-11 13:43
That's a startup log, I don't see anything relevant to errors with OPNsense integration.

**Comment by perdicaro** [comment] 2023-01-11 13:50
> > I have debugging enabled in opnsense integrations, where can I find the log it creates?
> 
> It's an integration, doesn't have separate log, you should check HA logs...look for "opnsense"

![2023-01-11 13_50_48-](https://user-images.githubusercontent.com/65085739/211823038-4ec9aacc-f2b1-4ba7-8f91-68276cdf3710.jpg)


i can`t find opnsense LOG

**Comment by travisghansen** [comment] 2023-01-11 20:17
Should be the top one I think (I don't use hass os but that looks like the likely option).

**Comment by perdicaro** [comment] 2023-01-11 20:34
> Should be the top one I think (I don't use hass os but that looks like the likely option).

sorry i can't understand what you mean, hass is it a log plugin on home assistant?

**Comment by perdicaro** [comment] 2023-01-11 20:58
`2023-01-11 15:44:33.168 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 30 and 43
2023-01-11 15:44:33.494 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration opnsense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 15:44:33.497 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 15:44:33.499 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration discord_game which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 15:44:33.500 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-11 15:44:49.141 WARNING (MainThread) [homeassistant.config_entries] Config entry '10.10.10.62:19444' for hyperion integration not ready yet: None; Retrying in background
2023-01-11 15:45:01.225 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-01-11 15:45:01.246 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esphome-web-f01d44 @ 10.10.10.68: Error connecting to ('10.10.10.68', 6053): [Errno 113] Connect call failed ('10.10.10.68', 6053)
2023-01-11 15:45:01.251 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WLED Corridoio' for wled integration not ready yet: Invalid response from API: Error occurred while communicating with WLED device at 10.10.10.70; Retrying in background
2023-01-11 15:45:19.880 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2023-01-11 15:45:19.888 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2023-01-11 16:58:53.051 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Timeout occurred while connecting to WLED device at 10.10.10.70
2023-01-11 17:05:02.063 ERROR (MainThread) [homeassistant.components.wled] Error fetching wled data: Invalid response from API: Error occurred while communicating with WLED device at 10.10.10.70
2023-01-11 19:08:00.815 ERROR (MainThread) [homeassistant.components.octoprint] Error requesting octoprint-b2f1641bac778e7da5ed051074e1692e data: Cannot connect to host 10.10.10.37:80 ssl:default [Connect call failed ('10.10.10.37', 80)]
2023-01-11 21:15:54.151 ERROR (MainThread) [reolink_aio.api] Host 10.10.10.27:443: content type error: Expected type 'image/jpeg' but received 'text/html'..
2023-01-11 21:15:54.181 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 724, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 742, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 170, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/usr/src/homeassistant/homeassistant/components/reolink/camera.py", line 70, in async_camera_image
    return await self._host.api.get_snapshot(self._channel)
  File "/usr/local/lib/python3.10/site-packages/reolink_aio/api.py", line 1179, in get_snapshot
    response = await self.send(None, param, expected_content_type="image/jpeg")
  File "/usr/local/lib/python3.10/site-packages/reolink_aio/api.py", line 2778, in send
    raise e
  File "/usr/local/lib/python3.10/site-packages/reolink_aio/api.py", line 2731, in send
    raise InvalidContentTypeError(f"Expected type '{expected_content_type}' but received '{response.content_type}'.")
reolink_aio.exceptions.InvalidContentTypeError: Expected type 'image/jpeg' but received 'text/html'.
`

**Comment by perdicaro** [comment] 2023-01-11 20:59
i found some errors about opnsense plugin

**Comment by alexdelprete** [comment] 2023-01-12 00:01
> i found some errors about opnsense plugin

if you refer to this:

> We found a custom integration opnsense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

that is a generic warning HA for every custom component. it's not an error regarding opnsense custom component.

**Comment by perdicaro** [comment] 2023-01-12 06:20
> > ho trovato alcuni errori sul plug-in opnsense
> 
> se ti riferisci a questo :
> 
> > Abbiamo trovato un opnsense di integrazione personalizzato che non è stato testato da Home Assistant. Questo componente potrebbe causare problemi di stabilità, assicurati di disabilitarlo in caso di problemi con Home Assistant
> 
> questo è un avviso generico HA per ogni componente personalizzato. non è un errore relativo al componente personalizzato di opnsense.

ok

**Comment by travisghansen** [comment] 2023-01-15 22:25
What version of opnsense are you both running? I can't reproduce the issue with `22.7.10`.

**Comment by alexdelprete** [comment] 2023-01-15 23:08
> What version of opnsense are you both running?

OPNsense 22.7.10_2-amd64

**Comment by travisghansen** [comment] 2023-01-15 23:08
I've noticed that the logbook shows unavailable but the the entity is working as designed. Do you see the versions etc in the widget details? Can you send a screenshot?

**Comment by alexdelprete** [comment] 2023-01-15 23:10
You mean the sysinfo OPNsense widget?

![image](https://user-images.githubusercontent.com/7027842/212572393-952fcd1b-099d-49f1-8c63-b426dae7ecea.png)

**Comment by travisghansen** [comment] 2023-01-15 23:11
In hass. Navigate to the integration, then device, then click the update sensor in the 'diagnostic' section.

**Comment by alexdelprete** [comment] 2023-01-15 23:12
![image](https://user-images.githubusercontent.com/7027842/212572455-64d5b0f3-15ff-468b-8877-89c121b4b966.png)

**Comment by travisghansen** [comment] 2023-01-15 23:15
Apply the below and restart hass and maybe that will help.

```
diff --git a/custom_components/opnsense/update.py b/custom_components/opnsense/update.py
index 7cc0102..390210d 100644
--- a/custom_components/opnsense/update.py
+++ b/custom_components/opnsense/update.py
@@ -94,6 +94,7 @@ class OPNSenseFirmwareUpdatesAvailableUpdate(OPNSenseUpdate):
     @property
     def available(self):
         state = self.coordinator.data
+        print(state["firmware_update_info"])
         if state["firmware_update_info"] is None:
             return False
```

**Comment by alexdelprete** [comment] 2023-01-15 23:26
Can't see anything in HA logs, I now enabled debug in logger: `custom_components.opnsense: debug`

Restarting and checking again...

**Comment by alexdelprete** [comment] 2023-01-15 23:29
These are the only relevant things I see in HA logs in debug mode:

```
2023-01-16 00:25:54.271 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_system_info 0.048
2023-01-16 00:25:54.374 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_host_firmware_version 0.102
2023-01-16 00:25:54.390 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_firmware_update_info 0.016
2023-01-16 00:25:54.854 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_telemetry 0.465
2023-01-16 00:25:54.915 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_config 0.061
2023-01-16 00:25:55.007 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_interfaces 0.092
2023-01-16 00:25:55.117 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_services 0.109
2023-01-16 00:25:55.175 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_carp_interfaces 0.058
2023-01-16 00:25:55.241 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_carp_status 0.067
2023-01-16 00:25:55.275 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._are_notices_pending 0.033
2023-01-16 00:25:55.326 DEBUG (SyncWorker_4) [custom_components.opnsense] execution time: OPNSenseData._get_notices 0.051
2023-01-16 00:25:55.327 DEBUG (MainThread) [custom_components.opnsense] Finished fetching OPNsense OPNsense state data in 1.109 seconds (success: True)
2023-01-16 00:26:25.275 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_system_info 0.046
2023-01-16 00:26:25.314 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_host_firmware_version 0.038
2023-01-16 00:26:25.329 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_firmware_update_info 0.015
2023-01-16 00:26:25.805 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_telemetry 0.475
2023-01-16 00:26:25.856 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_config 0.051
2023-01-16 00:26:25.906 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_interfaces 0.05
2023-01-16 00:26:26.006 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_services 0.1
2023-01-16 00:26:26.062 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_carp_interfaces 0.056
2023-01-16 00:26:26.094 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_carp_status 0.032
2023-01-16 00:26:26.125 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._are_notices_pending 0.031
2023-01-16 00:26:26.156 DEBUG (SyncWorker_11) [custom_components.opnsense] execution time: OPNSenseData._get_notices 0.03
2023-01-16 00:26:26.157 DEBUG (MainThread) [custom_components.opnsense] Finished fetching OPNsense OPNsense state data in 0.939 seconds (success: True)
```

**Comment by travisghansen** [comment] 2023-01-15 23:31
Change it to this then..

```
_LOGGER.debug(state["firmware_update_info"])
```

**Comment by alexdelprete** [comment] 2023-01-15 23:38
Last line should be the _LOGGER.debug right? It's NONE.

```
2023-01-16 00:35:03.475 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_system_info 0.037
2023-01-16 00:35:03.516 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_host_firmware_version 0.041
2023-01-16 00:35:03.543 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_firmware_update_info 0.026
2023-01-16 00:35:04.064 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_telemetry 0.521
2023-01-16 00:35:04.122 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_config 0.058
2023-01-16 00:35:04.207 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_interfaces 0.085
2023-01-16 00:35:04.347 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_services 0.139
2023-01-16 00:35:04.403 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_carp_interfaces 0.056
2023-01-16 00:35:04.480 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_carp_status 0.077
2023-01-16 00:35:04.511 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._are_notices_pending 0.031
2023-01-16 00:35:04.542 DEBUG (SyncWorker_9) [custom_components.opnsense] execution time: OPNSenseData._get_notices 0.031
2023-01-16 00:35:04.543 DEBUG (MainThread) [custom_components.opnsense] Finished fetching OPNsense OPNsense state data in 1.118 seconds (success: True)
2023-01-16 00:35:04.545 DEBUG (MainThread) [custom_components.opnsense.update] None
```

**Comment by travisghansen** [comment] 2023-01-15 23:47
Can you follow the instructions here to get the status data using pure curl? https://docs.opnsense.org/development/api/core/firmware.html

```
curl -k -u "$key":"$secret" https://opnsense.local/api/core/firmware/status -v
```

**Comment by alexdelprete** [comment] 2023-01-16 00:01
> Can you follow the instructions here to get the status data using pure curl?

```json
{
  "api_version": "2",
  "connection": "ok",
  "downgrade_packages": [],
  "download_size": "",
  "last_check": "Mon Jan 16 00:08:28 CET 2023",
  "needs_reboot": "0",
  "new_packages": [],
  "os_version": "FreeBSD 13.1-RELEASE-p5",
  "product_id": "opnsense",
  "product_target": "opnsense",
  "product_version": "22.7.10_2",
  "reinstall_packages": [],
  "remove_packages": [],
  "repository": "ok",
  "upgrade_major_message": "",
  "upgrade_major_version": "",
  "upgrade_needs_reboot": "0",
  "upgrade_packages": [],
  "upgrade_sets": [],
  "product": {
    "product_abi": "22.7",
    "product_arch": "amd64",
    "product_check": {
      "api_version": "2",
      "connection": "ok",
      "downgrade_packages": [],
      "download_size": "",
      "last_check": "Mon Jan 16 00:08:28 CET 2023",
      "needs_reboot": "0",
      "new_packages": [],
      "os_version": "FreeBSD 13.1-RELEASE-p5",
      "product_id": "opnsense",
      "product_target": "opnsense",
      "product_version": "22.7.10_2",
      "reinstall_packages": [],
      "remove_packages": [],
      "repository": "ok",
      "upgrade_major_message": "",
      "upgrade_major_version": "",
      "upgrade_needs_reboot": "0",
      "upgrade_packages": [],
      "upgrade_sets": []
    },
    "product_copyright_owner": "Deciso B.V.",
    "product_copyright_url": "https://www.deciso.com/",
    "product_copyright_years": "2014-2022",
    "product_crypto": "OpenSSL",
    "product_email": "project@opnsense.org",
    "product_flavour": "OpenSSL",
    "product_hash": "bdce9463f",
    "product_id": "opnsense",
    "product_latest": "22.7.10",
    "product_license": [],
    "product_log": 0,
    "product_mirror": "https://pkg.opnsense.org/FreeBSD:13:amd64/22.7",
    "product_name": "OPNsense",
    "product_nickname": "Powerful Panther",
    "product_repos": "OPNsense, mimugmail, ntop",
    "product_series": "22.7",
    "product_time": "Fri Dec 23 03:52:21 CET 2022",
    "product_version": "22.7.10_2",
    "product_website": "https://opnsense.org/"
  },
  "all_packages": [],
  "all_sets": [],
  "status_msg": "There are no updates available on the selected mirror.",
  "status": "none"
}
```

**Comment by travisghansen** [comment] 2023-01-16 00:09
Hmm, that’s basically all the integration does. Did you use the same key/secret as hass has?

Any chance you can reach out privately (discord, email, whatever) and discuss and get me temporary access to the api?

**Comment by alexdelprete** [comment] 2023-01-16 00:15
> Did you use the same key/secret as hass has?

I double-checked in core-config_entries, it's the same key/secret, user=$key and password=$secret.

You can find me on Discord: `alexdelprete#5566`

**Comment by perdicaro** [comment] 2023-01-16 00:20
I followed the discussion, if there is news about a fix, will you update me? thank you

**Comment by alexdelprete** [comment] 2023-01-16 00:58
> I followed the discussion, if there is news about a fix, will you update me? thank you

Travis is fixing it now, you will see a new version notification in HACS.

**Comment by perdicaro** [comment] 2023-01-16 01:08
> > I followed the discussion, if there is news about a fix, will you update me? thank you
> 
> Travis is fixing it now, you will see a new version notification in HACS when it will be released.

fantastic! Thanks so much!

**Comment by travisghansen** [comment] 2023-01-16 16:32
Please try `v0.1.6`

**Comment by perdicaro** [comment] 2023-01-16 16:37
![2023-01-16 17_36_52-Impostazioni – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/212727492-05a965f8-fd6f-4659-afa8-92864d1d3998.jpg)
still same, "not disponible" i install the update and reboot

**Comment by travisghansen** [comment] 2023-01-16 17:46
Please try `v0.1.7` now.

**Comment by alexdelprete** [comment] 2023-01-16 17:47
And please close the issue once verified working. ;)

**Comment by perdicaro** [comment] 2023-01-16 17:50
![2023-01-16 18_49_19-Panoramica – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/212739600-e1c9f986-e2bf-4545-a78c-9fbf42f27deb.jpg)
Thnx for your work and helping!!!
![2023-01-16 18_49_19-Panoramica – Home Assistant - Vivaldi](https://user-images.githubusercontent.com/65085739/212739650-dfbbc5d7-8afd-4751-b135-a5d20bbba067.jpg)

**Comment by travisghansen** [comment] 2023-01-16 17:51
Great!

**Closed** 2023-01-16 17:50 UTC
