### ISSUE TITLE
Invalid uptime format

### ISSUE THREAD

**Issue by Riza-Aslan** [travisghansen/hass-opnsense#170] opened 2024-09-08 08:53 UTC
I've upgraded the Plugin to version 0.2.0, deleted the old configuration and tried to set it up again. But the integration tells me "Invalid uptime format". The opnsense-user has the necessary permissions (same as listed in the readme) and i've created a new API-Key, but it doesn't work.

![image](https://github.com/user-attachments/assets/53ed8294-d2a8-4f45-80ed-b93df3e7ed6e)

**Comment by alexdelprete** [comment] 2024-09-08 08:55
Please enable debug and post the debug log after reloading the integration.

Plus: did you try with the recommended admin user?

**Comment by Riza-Aslan** [comment] 2024-09-08 09:01
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.opnsense
Quelle: helpers/update_coordinator.py:354
Integration: OPNsense (Dokumentation, Probleme)
Erstmals aufgetreten: 7. September 2024 um 14:19:59 (30 Vorkommnisse)
Zuletzt protokolliert: 10:58:15

Unexpected error fetching As-Sense OPNsense state data
Unexpected error fetching AsSense OPNsense state data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
                                              ^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 317, in update
    self._state["telemetry"] = self._get_telemetry()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 226, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 250, in _get_telemetry
    return self._client.get_telemetry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 926, in get_telemetry
    telemetry["system"] = self._get_telemetry_system()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1132, in _get_telemetry_system
    raise ValueError("Invalid uptime format")
ValueError: Invalid uptime format`

Yesterday I used the root user and it didn't work. Today, i tried it with my seperate "homeassistant" user and give him the needed permissions.

**Comment by Riza-Aslan** [comment] 2024-09-08 09:04
And yes...the homeassistant user has the admin-role:

![image](https://github.com/user-attachments/assets/318cdb4e-2301-4abf-aeb8-7d8e20394901)

**Comment by alexdelprete** [comment] 2024-09-08 09:07
That is not the debug log, can you enable debug on the integration page first? thanks.

**Comment by Riza-Aslan** [comment] 2024-09-08 09:11
I'm sorry. It is enabled, but I don't know where to find the log (never used it before). This was the Home Assistant Core Log. Could you tell me where I can find the Log for integrations?

**Comment by alexdelprete** [comment] 2024-09-08 09:18
if you enable debug and reload the integration, then wait a few secs, if you disable debug it should download the log. :)

alternatively, once you enable debug, go to `Settings->System->Logs` and click on `Load Full Logs` to monitor it:

![image](https://github.com/user-attachments/assets/7c7ba07a-2b48-4982-81cc-e678cea54d87)

**Comment by Riza-Aslan** [comment] 2024-09-08 09:28
Thank you...got it. But I had to remove some lines, because it listed all my firewall information. Hope this is enough. Otherwise just tell me what exactly you need:

2024-09-08 11:21:12.177 DEBUG (SyncWorker_26) [custom_components.opnsense] execution time: OPNSenseData._get_system_info 0.144
2024-09-08 11:21:12.350 DEBUG (SyncWorker_26) [custom_components.opnsense] execution time: OPNSenseData._get_host_firmware_version 0.173
2024-09-08 11:21:12.699 DEBUG (SyncWorker_26) [custom_components.opnsense] execution time: OPNSenseData._get_firmware_update_info 0.348
2024-09-08 11:21:13.489 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_interfaces] interface_info: [{'flags': ['broadcast', 'simplex', 'multicast'], 
2024-09-08 11:21:13.490 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_interfaces] interfaces: {}
2024-09-08 11:21:13.592 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_mbuf] mbuf_info: {'message': 'action system_mbuf not found', 'status': 400}
2024-09-08 11:21:13.592 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_mbuf] mbuf: {'used': None, 'total': None, 'used_percent': None}
2024-09-08 11:21:13.678 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_pfstate] pfstate_info: {'message': 'action pf_states not found', 'status': 400}
2024-09-08 11:21:13.678 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_pfstate] pfstate: {'used': None, 'total': None, 'used_percent': None}
2024-09-08 11:21:13.791 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_memory] memory_info: {'message': 'action systemResources not found', 'status': 400}
2024-09-08 11:21:13.879 ERROR (SyncWorker_26) [custom_components.opnsense.pyopnsense] Unable to get Swap data. Ensure the OPNsense user connected to HA either has full Admin access or specifically has the 'Dashboard (all)' privilege.
2024-09-08 11:21:13.967 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_system] time_info: {'message': 'action systemTime not found', 'status': 400}
2024-09-08 11:21:13.968 ERROR (SyncWorker_26) [custom_components.opnsense.pyopnsense] Unexpected _get_telemetry_system error err=ValueError('Invalid uptime format'), type(err)=<class 'ValueError'>
2024-09-08 11:21:13.968 ERROR (SyncWorker_26) [custom_components.opnsense.pyopnsense] Unexpected get_telemetry error err=ValueError('Invalid uptime format'), type(err)=<class 'ValueError'>
2024-09-08 11:21:13.969 ERROR (MainThread) [custom_components.opnsense] Unexpected error fetching AsSense OPNsense state data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 98, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
                                              ^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 317, in update
    self._state["telemetry"] = self._get_telemetry()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 226, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 250, in _get_telemetry
    return self._client.get_telemetry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 926, in get_telemetry
    telemetry["system"] = self._get_telemetry_system()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 104, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 101, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1132, in _get_telemetry_system
    raise ValueError("Invalid uptime format")
ValueError: Invalid uptime format
2024-09-08 11:21:13.969 DEBUG (MainThread) [custom_components.opnsense] Finished fetching AsSense OPNsense state data in 1.937 seconds (success: False)

**Comment by alexdelprete** [comment] 2024-09-08 10:12
In that screenshot above, check "search logs", you can input a string (opnsense) so the log will be automatically filtered. It's a grep. :)

**Comment by Snuffy2** [comment] 2024-09-08 14:00
```
2024-09-08 11:21:13.489 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_interfaces] interface_info: [{'flags': ['broadcast', 'simplex', 'multicast']
2024-09-08 11:21:13.592 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_mbuf] mbuf_info: {'message': 'action system_mbuf not found', 'status': 400}
2024-09-08 11:21:13.678 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_pfstate] pfstate_info: {'message': 'action pf_states not found', 'status': 400}
2024-09-08 11:21:13.791 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_memory] memory_info: {'message': 'action systemResources not found', 'status': 400}
2024-09-08 11:21:13.967 DEBUG (SyncWorker_26) [custom_components.opnsense.pyopnsense] [get_telemetry_system] time_info: {'message': 'action systemTime not found', 'status': 400}
```

Some pending updates should have this fail more gracefully. However, you are getting `400 Bad Request` errors with every query to the OPNsense REST API. I see that the OPNsense user correctly has Admin access. 

Ensure that the URL you entered when you added the integration and the API Key and Secret are correct.

What version of OPNsense and Home Assistant are you running?

**Comment by cayubweeums** [comment] 2024-09-08 14:45
Hey All!

I am having the same issues as OP here. 

@Snuffy2 My OPNSense version is `24.1.10_8` and my HA version is `2024.9.1`. I have validated that the URL and API secret/key are correct. It was able to pull the host name of the firewall automatically so it seems to have some amount of success during the init process?

**Comment by alexdelprete** [comment] 2024-09-08 16:39
> Ensure that the URL you entered when you added the integration and the API Key and Secret are correct.

wouldn't a wrong URL cause 404 vs 400? 400 indicates something on the client side request format. That's why I thought about GET vs POST.

**Comment by Snuffy2** [comment] 2024-09-08 19:59
Most of the queries we are using work with Get or Post since there aren't any variables being sent to the requests. I'll clean them up to use the documented method but I don't believe this is the cause.
It _shouldn't_ give a 400 response, but I'm just covering all bases.

@cayubweeums yes, the fact that you are getting some data does indicate some part of it are working.
@Riza-Aslan are you also running OPNsense 24.1 or earlier? I wonder if the REST API commands being used for the Telemetry data are 24.7+

**Comment by Snuffy2** [comment] 2024-09-08 20:19
Most of the REST API Endpoints being used in v0.2.0 of the integration were added to the Documentation on 7/25/24 which is the same date OPNsense 24.7 was released.

I could add back the XMLRPC functions and use the different functions depending on the OPNsense version number I think.

**Comment by alexdelprete** [comment] 2024-09-08 22:25
> I could add back the XMLRPC functions and use the different functions depending on the OPNsense version number I think. But maintaining parallel functions long-term will be a pain.

I think it's not needed. The way forward is the REST API, like OPNsense devs confirmed, XMLrpc might be dropped sooner than expected.

**Comment by Snuffy2** [comment] 2024-09-08 23:43
Adding back the old function was easier than I expected. Let's at least add that back in for now.

@alexdelprete I'm putting together a document tracking what functions are currently using the REST API and what is using XMLRPC. For the ones using XMLRPC, some of them are still not available in the REST API, but plenty are. I'll put my findings on that as well.

**Comment by Snuffy2** [comment] 2024-09-09 00:03
@alexdelprete Lets put #173 and earlier out as a beta to see if it actually works for this issue since I can't test it myself.

Note that in OPNsense < 24.7, the following entities won't work (should be part of the final release notes):
* Temperature sensors
* CPU Usage
* _Possibly others_

**Comment by alexdelprete** [comment] 2024-09-09 01:36
> I'm putting together a document tracking what functions are currently using the REST API and what is using XMLRPC.

That is an excellent idea.

> Lets put #173 and earlier out as a beta to see if it actually works for this issue since I can't test it myself.

I'll release a beta now.

**Comment by alexdelprete** [comment] 2024-09-09 01:42
@Riza-Aslan @cayubweeums we have released [v0.2.1-beta.1](https://github.com/travisghansen/hass-opnsense/releases/tag/v0.2.1-beta.1) to be tested, please give us a feedback.

**Comment by cpw** [comment] 2024-09-09 01:46
I just installed the 0.2.1-beta.1 version, and am running 24.1.10_3 OPN sense version. I hit this exact problem prior to the update. The beta update resolved it, thanks!

**Comment by Riza-Aslan** [comment] 2024-09-09 05:15
Sorry, but when I've seen that there is a new OPNsense version i just upgraded. I cannot try the beta anymore, but 0.2.0 is now working for me.

Thank you both for your quick help!

**Comment by alexdelprete** [comment] 2024-09-09 09:55
I guess we can close the issue now.

Thanks for the feedbacks.

**Closed by alexdelprete** 2024-09-09 09:55 UTC
