### ISSUE TITLE
KeyError: 'name' issue

### ISSUE THREAD

**Issue by KillSwitchSIG** [travisghansen/hass-opnsense#77] opened 2023-04-16 07:14 UTC
I am getting the below error in the HA logs and the integration is not polling updates at the regular interval.

Logger: homeassistant.components.switch
Source: custom_components/opnsense/switch.py:172
Integration: Switch (documentation, issues)
First occurred: 3:05:49 PM (2 occurrences)
Last logged: 3:09:15 PM

Error while setting up opnsense platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/opnsense/switch.py", line 190, in async_setup_entry
    cem.process_entities()
  File "/config/custom_components/opnsense/__init__.py", line 471, in process_entities
    entities = self.process_entities_callback(self.hass, self.config_entry)
  File "/config/custom_components/opnsense/switch.py", line 172, in process_entities_callback
    key="service.{}.{}".format(service["name"], property),
KeyError: 'name'

**Comment by xitation** [comment] 2024-01-22 04:10
I'm also seeing the same errors on HA 2024.1.2 and OPNsense 23.7.11-amd6, with the OpnSense addon version os-homeassistant-maxit 1.0.

Let me know if you need more info, logs, etc, happy to share/assist.

**Comment by alexdelprete** [comment] 2024-01-22 22:03
I have no errors in the log, and I'm on HA 2024.1.4.

The only errors I had was due to warnings for changed constants in HA 2024, I prepared PR #112 with the necessary changes to avoid the warnings.

You can use this version attached while waiting for the PR to be merged: [hass-opnsense-2024.1-patch-v2.zip](https://github.com/travisghansen/hass-opnsense/files/13864856/hass-opnsense-2024.1-patch-v2.zip)

**Comment by xitation** [comment] 2024-01-23 05:32
`Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]: 2024-01-23 16:29:57.630 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]: Traceback (most recent call last):
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:     await self._async_refresh(log_failures=True, scheduled=True)
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:     self.async_update_listeners()
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:     update_callback()
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:   File "/config/custom_components/opnsense/__init__.py", line 471, in process_entities
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:     entities = self.process_entities_callback(self.hass, self.config_entry)
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:   File "/config/custom_components/opnsense/switch.py", line 172, in process_entities_callback
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:     key="service.{}.{}".format(service["name"], property),
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]:                                ~~~~~~~^^^^^^^^
Jan 23 05:29:57 Xi-Hassio-1 homeassistant[523]: KeyError: 'name'
`

Is the error I keep seeing in the logs, seems to happen pretty regularly, like every 30-40 seconds or so.

**Comment by xitation** [comment] 2024-01-23 05:35
> I have no errors in the log, and I'm on HA 2024.1.4.
> 
> The only thing I had in the logs were due to warnings for changed constants in HA 2024, I prepared PR #112 with the necessary changes to avoid the warnings.
> 
> You can use this version attached while waiting for the PR to be merged: [hass-opnsense-2024.1-patch-v2.zip](https://github.com/travisghansen/hass-opnsense/files/13864856/hass-opnsense-2024.1-patch-v2.zip)

I've added this PR to my install, but has not made a difference to the error showing up every 30-40 seconds.

**Comment by alexdelprete** [comment] 2024-01-23 13:37
> I've added this PR to my install, but has not made a difference to the error showing up every 30-40 seconds.

That PR is just for warnings in the log related to new ENUM types introduced, that create warnings in the log. Not related to this specific issue.



> I run a custom CA and have a server cert issued by this CA on OpnSense, I use this addon to allow for TLS trustchain to be loaded into HA - https://github.com/Athozs/hass-additional-ca in case this is anyway relevant.

Don't know if it's relevant or not, I'm using http on the internal LAN, never understood the need to use https internally, but just in case, could you try an http connection with the same user just to test?

**Comment by tman785** [comment] 2024-03-20 02:34
Want to add this in - was getting a simliar name error and narrowed down to enabling opn-arp.  As soon as I disabled it, the error went away.  This issue I was seeing was that I could not use any firewall rules as switches in HA.  I believe there's another report of this issue as well, but not directly related to lack of firewall rule access.

**Comment by xitation** [comment] 2024-04-09 10:55
I've removed the opn-arp addon and it seems to have cleared up the issue my end too. Odd.

I'll keep an eye on it in case I was just not patient enough to see the log entries. But it usually happened pretty regularly, and I've not seen it since removing the opn-arp package on the Opnsense instance. 

Not sure who needs to fix this bug then? Is it a bug with this package? or the Opn-Arp package?

**Comment by tman785** [comment] 2024-04-09 15:22
I looked at the opn-arp code, I dont see how enabling it affects anything else.  It's just reading the arp table and comparing against a "text db".  Unless enabling the service itself ties up a specific resource.  My guess is that the issue is with the ha package on opnsense vs opn-arp service.  

You dont need to remove opn-arp, just disable it.

**Comment by xitation** [comment] 2024-04-10 00:20
Pretty sure the Opn-Arp and HA packages on Opnsense are from the same maintainer.  Maybe I'll try and raise a bug report.

I guess there isn't much point leaving it installed if it's disabled though :)

**Comment by tman785** [comment] 2024-04-10 02:10
Looks like someone already opened an issue: https://github.com/mimugmail/opn-repo/issues/194

Needs more investigation though.

**Comment by alexdelprete** [comment] 2024-09-07 09:54
Please test v0.2.0 and in case open another issue.

**Closed by alexdelprete** 2024-09-07 09:54 UTC
