### ISSUE TITLE
STATE_CLASS_MEASUREMENT was used from opnsense, this is a deprecated constant 

### ISSUE THREAD

**Issue by mjpiratex** [travisghansen/hass-opnsense#117] opened 2024-01-26 09:20 UTC
Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:205
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 3:17:39 AM (4 occurrences)
Last logged: 3:17:41 AM

STATE_CLASS_MEASUREMENT was used from opnsense, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/travisghansen/hass-opnsense/issues

**Comment by alexdelprete** [comment] 2024-01-26 12:29
Duplicate of #111

See my comment here: https://github.com/travisghansen/hass-opnsense/issues/111#issuecomment-1881607874

**Closed** 2024-09-07 01:00 UTC
