### ISSUE TITLE
[Bug]: Long startup time

### ISSUE THREAD

**Issue by Inglan** [travisghansen/hass-opnsense#338] opened 2024-12-08 03:29 UTC
### What happened?

This integration takes around 30 seconds to startup. ZHA (second slowest startup time in my instance) starts in about 10 seconds
![image](https://github.com/user-attachments/assets/ba5d7df9-bb36-4e30-bdc9-6cda2f47c22f)
Not sure why this integration is so slow at starting.

### hass-opnsense Version

13.2

### OPNsense Firmware

24.7.7

### Home Assistant Version

2024.11.3

**Comment by alexdelprete** [comment] 2024-12-08 09:23
9s here:

![image](https://github.com/user-attachments/assets/9dd93894-5e10-4d7e-bb8e-5f10f1ed6284)

**Comment by alexdelprete** [comment] 2024-12-08 09:29
Please provide some context: hw platform used by HA, are you using IP or hostname in the integration config to point to opnsense instance, etc.

The integration makes a lot of REST API calls. DNS lookup could be a potential issue (happened with other users), but there might be other factors.

Also, you can enable debug on the integration, reload it, then check the log and timestamps, to see where the delays are.

**Comment by Inglan** [comment] 2024-12-09 01:37
Here are my logs:
```
2024-12-09 12:28:28.451 INFO (MainThread) [custom_components.opnsense] Starting hass-opnsense v0.3.11
2024-12-09 12:28:28.451 INFO (MainThread) [custom_components.opnsense.coordinator] Initializing OPNsense Data Update Coordinator 
2024-12-09 12:28:28.451 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/interfaces/overview/export
2024-12-09 12:28:29.738 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:29.751 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_device_unique_id] device_unique_id: [ROUTER UNIQUE ID]
2024-12-09 12:28:29.751 DEBUG (MainThread) [custom_components.opnsense] [init async_setup_entry]: config device id: [ROUTER UNIQUE ID], router device id: [ROUTER UNIQUE ID]
2024-12-09 12:28:29.751 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/core/firmware/status
2024-12-09 12:28:30.227 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:30.231 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_host_firmware_version] firmware: 24.7.10_2
2024-12-09 12:28:30.231 INFO (MainThread) [custom_components.opnsense] OPNsense Firmware 24.7.10_2
2024-12-09 12:28:30.232 INFO (MainThread) [custom_components.opnsense.coordinator] Updating Data
2024-12-09 12:28:30.232 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/interfaces/overview/export
2024-12-09 12:28:31.420 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:31.426 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_device_unique_id] device_unique_id: [ROUTER UNIQUE ID]
2024-12-09 12:28:31.426 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_device_unique_id: 1.194 seconds
2024-12-09 12:28:31.426 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/core/firmware/status
2024-12-09 12:28:31.887 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:31.887 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_host_firmware_version] firmware: 24.7.10_2
2024-12-09 12:28:31.887 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_host_firmware_version: 0.461 seconds
2024-12-09 12:28:31.888 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/diagnostics/system/systemInformation
2024-12-09 12:28:32.406 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:32.406 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_system_info: 0.519 seconds
2024-12-09 12:28:32.407 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/core/firmware/status
2024-12-09 12:28:32.871 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:32.872 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_firmware_update_info: 0.465 seconds
2024-12-09 12:28:32.873 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/system/system_mbuf
2024-12-09 12:28:32.873 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:33.424 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:33.424 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/firewall/pf_states
2024-12-09 12:28:33.424 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:33.532 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:33.532 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/system/systemResources
2024-12-09 12:28:33.532 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:33.935 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:33.936 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/system/system_swap
2024-12-09 12:28:33.936 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:34.261 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:34.268 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/system/systemTime
2024-12-09 12:28:34.268 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:34.656 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:34.656 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/cpu_usage/getCPUType
2024-12-09 12:28:34.656 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:35.045 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:35.045 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_from_stream] url: https://[ROUTER IP]/api/diagnostics/cpu_usage/stream
2024-12-09 12:28:35.369 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_from_stream] Response 200: OK
2024-12-09 12:28:36.366 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] url: https://[ROUTER IP]/api/diagnostics/system/systemDisk
2024-12-09 12:28:36.366 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] payload: None
2024-12-09 12:28:36.492 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [post] Response 200: OK
2024-12-09 12:28:36.492 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/diagnostics/system/systemTemperature
2024-12-09 12:28:36.976 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:36.976 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_telemetry: 4.105 seconds
2024-12-09 12:28:36.976 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/interfaces/overview/export
2024-12-09 12:28:38.259 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:38.284 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_interfaces: 1.307 seconds
2024-12-09 12:28:38.284 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/openvpn/service/searchSessions
2024-12-09 12:28:38.786 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:38.787 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/openvpn/service/searchRoutes
2024-12-09 12:28:39.259 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:39.260 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/openvpn/export/providers
2024-12-09 12:28:39.724 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:39.731 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/openvpn/instances/search
2024-12-09 12:28:39.897 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:39.898 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/openvpn/instances/get/1
2024-12-09 12:28:40.073 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:40.075 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_openvpn] openvpn: [REDACTED]
2024-12-09 12:28:40.076 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_openvpn: 1.792 seconds
2024-12-09 12:28:40.076 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/routes/gateway/status
2024-12-09 12:28:40.438 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:40.438 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_gateways: 0.363 seconds
2024-12-09 12:28:42.666 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_config: 2.227 seconds
2024-12-09 12:28:42.666 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/core/service/search
2024-12-09 12:28:43.642 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:43.643 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_services: 0.977 seconds
2024-12-09 12:28:43.643 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/interfaces/vip_settings/get
2024-12-09 12:28:43.741 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:43.741 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/diagnostics/interface/get_vip_status
2024-12-09 12:28:44.342 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:44.342 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_carp_interfaces] carp: []
2024-12-09 12:28:44.342 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_carp_interfaces: 0.699 seconds
2024-12-09 12:28:44.343 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/diagnostics/interface/get_vip_status
2024-12-09 12:28:44.915 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:44.917 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_carp_status: 0.575 seconds
2024-12-09 12:28:44.917 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/core/system/status
2024-12-09 12:28:45.156 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:45.156 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_notices: 0.239 seconds
2024-12-09 12:28:45.156 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/unbound/settings/get
2024-12-09 12:28:45.322 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:45.323 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_unbound_blocklist: 0.167 seconds
2024-12-09 12:28:45.323 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/kea/leases4/search
2024-12-09 12:28:46.378 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:46.402 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/kea/dhcpv4/searchReservation
2024-12-09 12:28:46.538 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:46.540 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/dhcpv4/leases/searchLease
2024-12-09 12:28:47.992 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:47.994 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/dhcpv6/leases/searchLease
2024-12-09 12:28:51.163 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:51.163 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/kea/dhcpv4/get
2024-12-09 12:28:51.267 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:51.268 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_dhcp_leases: 5.945 seconds
2024-12-09 12:28:51.268 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/wireguard/service/show
2024-12-09 12:28:51.753 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:51.753 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/wireguard/client/get
2024-12-09 12:28:51.951 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:51.951 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/wireguard/server/get
2024-12-09 12:28:52.123 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:52.124 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_wireguard: 0.856 seconds
2024-12-09 12:28:52.124 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] url: https://[ROUTER IP]/api/trust/cert/search
2024-12-09 12:28:52.306 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get] Response 200: OK
2024-12-09 12:28:52.306 DEBUG (MainThread) [custom_components.opnsense.pyopnsense] [get_certificates] certs: [REDACTED]
2024-12-09 12:28:52.306 DEBUG (MainThread) [custom_components.opnsense.coordinator] [Coordinator Timing] get_certificates: 0.183 seconds
2024-12-09 12:28:52.307 DEBUG (MainThread) [custom_components.opnsense.coordinator] [async_update_data] wireguard: {}
2024-12-09 12:28:52.307 DEBUG (MainThread) [custom_components.opnsense.coordinator] Update Complete. REST API Queries: 35. XMLRPC Queries: 1
2024-12-09 12:28:52.307 DEBUG (MainThread) [custom_components.opnsense.coordinator] Finished fetching Router state data in 22.075 seconds (success: True)
2024-12-09 12:28:52.328 DEBUG (MainThread) [custom_components.opnsense.sensor] [sensor async_setup_entry] entities: 141
2024-12-09 12:28:52.388 DEBUG (MainThread) [custom_components.opnsense.sensor] [OPNsenseDHCPLeasesSensor handle_coordinator_update] LAN: lease_count: 30
2024-12-09 12:28:52.388 DEBUG (MainThread) [custom_components.opnsense.sensor] [OPNsenseDHCPLeasesSensor handle_coordinator_update] Guest: lease_count: 1
2024-12-09 12:28:52.388 DEBUG (MainThread) [custom_components.opnsense.sensor] [OPNsenseDHCPLeasesSensor handle_coordinator_update] IoT: lease_count: 2
2024-12-09 12:28:52.389 DEBUG (MainThread) [custom_components.opnsense.switch] [switch async_setup_entry] entities: 22
```
Looks like it is making lots of calls to opnsense but not at the same time.

Also looks like its using an IP in the config.

I am running HA on generic machine (bare metal - no virtualization) with 8gb ram.

**Comment by Snuffy2** [comment] 2024-12-15 00:35
This appears to be working as designed.

**Comment by alexdelprete** [comment] 2024-12-15 02:01
> This appears to be working as designed.

I agree, it takes 8s here to complete the data update. It depends on the hw used (I have a MS-01 running OPNsense, bare-metal)

```python
2024-12-15 02:56:11.903 DEBUG (MainThread) [custom_components.opnsense.coordinator] Update Complete. REST API Queries: 34. XMLRPC Queries: 1
2024-12-15 02:56:11.903 DEBUG (MainThread) [custom_components.opnsense.coordinator] Finished fetching opnsense state data in 8.014 seconds (success: True)
```

**Comment by alexdelprete** [comment] 2024-12-15 02:05
> Looks like it is making lots of calls to opnsense but not at the same time.
> I am running HA on generic machine (bare metal - no virtualization) with 8gb ram.

The coordinator updates data at the same time. It's just that it takes a lot of time on your system. What cpu is it?

this is the summary of the coordinator data update session on your system:

```python
2024-12-09 12:28:52.307 DEBUG (MainThread) [custom_components.opnsense.coordinator] Update Complete. REST API Queries: 35. XMLRPC Queries: 1
2024-12-09 12:28:52.307 DEBUG (MainThread) [custom_components.opnsense.coordinator] Finished fetching Router state data in 22.075 seconds (success: True)
```

and this is mine (MS-01, the i5-12600H variant), takes 3 times less than yours:

```python
2024-12-15 02:56:11.903 DEBUG (MainThread) [custom_components.opnsense.coordinator] Update Complete. REST API Queries: 34. XMLRPC Queries: 1
2024-12-15 02:56:11.903 DEBUG (MainThread) [custom_components.opnsense.coordinator] Finished fetching opnsense state data in 8.014 seconds (success: True)
```

**Comment by alexdelprete** [comment] 2024-12-17 11:17
@Inglan since we don't see anything strange, I'll close this issue. Let us know in case you have other info.

**Closed by alexdelprete** 2024-12-17 11:17 UTC
Labels: bug
